name: evencir_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.2
  flutter_bloc: ^9.1.1  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svgs/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
          weight: 700 
